## Numpy ndarray 개요(nd: n차원, 예) 1차원, 2차원..)

In [5]:
import numpy as np
import matplotlib.pyplot as plt

# - 배열 생성

In [7]:
# - 1차원 배열(Vector) 정의
array1 = np.array([1,2,3])
print(array1) # [1 2 3] # ','가 없이 보여주는 것이 numpy
print('array1.type:', type(array1))
print('array1 array 형태:', array1.shape) # 행렬로 오해하지 말고 1차원이더라도 튜플 자료형 3, 으로 나온다. # 곧 3열을 의미
# shape은 차원을 결과로

[1 2 3]
array1.type: <class 'numpy.ndarray'>
array1 array 형태: (3,)


In [8]:
# cf) 리스트 자료형
list = [1,2,3]
print(list)
print('list.type:', type(list)) # 파이썬에서 알려주는 list

[1, 2, 3]
list.type: <class 'list'>


In [9]:
# - 2차원 배열(Vector) 정의
array2 = np.array([[1,2,3],[2,3,4]])
print(array2) # [1 2 3] # ,가 없이 보여주는 것이 numpy
print('array2.type:', type(array2))
print('array2 array 형태:', array2.shape) 

[[1 2 3]
 [2 3 4]]
array2.type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)


In [10]:
array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
