In [1]:
import tensorflow as tf
import numpy as np

In [4]:
xy = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32) 
# csv의 c는 comma # delimiter=','는 구분자를 말함 # float 4byte = 32bit
x_data = xy[:,0:-1] # 슬라이싱이기 때문에 생략가능 # ,로 접근하려면 반드시 []로 감싸줘야 한다.
y_data = xy[:,[-1]]

In [7]:
print(x_data, '\nx_data.shape:', x_data.shape)
print(y_data, '\ny_data.shape:', y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data.shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data.shape: (25, 1)


In [8]:
tf.model = tf.keras.Sequential()

tf.model.add(tf.keras.layers.Dense(input_dim=3, units=1, activation='linear')) # activation 생성해달라고 변수 선언을 해서 활성화해줌.

In [9]:
tf.model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [10]:
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(learning_rate=1e-5)) 
# learning_rate가 너무 커서 loss값이 크게 나오는 것이다.

In [11]:
tf.model.fit(x_data, y_data, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 0s 299ms/step - loss: 4399.4414
Epoch 2/2000
1/1 [==============================] - 0s 5ms/step - loss: 1632.3961
Epoch 3/2000
1/1 [==============================] - 0s 4ms/step - loss: 609.3417
Epoch 4/2000
1/1 [==============================] - 0s 4ms/step - loss: 231.0883
Epoch 5/2000
1/1 [==============================] - 0s 5ms/step - loss: 91.2361
Epoch 6/2000
1/1 [==============================] - 0s 4ms/step - loss: 39.5272
Epoch 7/2000
1/1 [==============================] - 0s 4ms/step - loss: 20.4074
Epoch 8/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.3368
Epoch 9/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.7209
Epoch 10/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.7522
Epoch 11/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.3924
Epoch 12/2000
1/1 [==============================] - 0s 5ms/step - loss: 9.2579
Epoch 13/2000
1/1 [=============

1/1 [==============================] - 0s 3ms/step - loss: 8.7362
Epoch 205/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.7341
Epoch 206/2000
1/1 [==============================] - 0s 5ms/step - loss: 8.7320
Epoch 207/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.7298
Epoch 208/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.7277
Epoch 209/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.7256
Epoch 210/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.7235
Epoch 211/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.7214
Epoch 212/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.7192
Epoch 213/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.7171
Epoch 214/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.7150
Epoch 215/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.7129
Epoch 216/2000
1/1 [=======================

1/1 [==============================] - 0s 4ms/step - loss: 8.3401
Epoch 407/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.3383
Epoch 408/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.3365
Epoch 409/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.3347
Epoch 410/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.3329
Epoch 411/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.3311
Epoch 412/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.3293
Epoch 413/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.3276
Epoch 414/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.3258
Epoch 415/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.3240
Epoch 416/2000
1/1 [==============================] - 0s 2ms/step - loss: 8.3222
Epoch 417/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.3204
Epoch 418/2000
1/1 [=======================

1/1 [==============================] - 0s 3ms/step - loss: 8.0056
Epoch 609/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.0040
Epoch 610/2000
1/1 [==============================] - 0s 4ms/step - loss: 8.0025
Epoch 611/2000
1/1 [==============================] - 0s 3ms/step - loss: 8.0010
Epoch 612/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9995
Epoch 613/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9980
Epoch 614/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9964
Epoch 615/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9949
Epoch 616/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9934
Epoch 617/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.9919
Epoch 618/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.9904
Epoch 619/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.9889
Epoch 620/2000
1/1 [=======================

1/1 [==============================] - 0s 3ms/step - loss: 7.7228
Epoch 811/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.7215
Epoch 812/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.7202
Epoch 813/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.7189
Epoch 814/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.7176
Epoch 815/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.7163
Epoch 816/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.7151
Epoch 817/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.7138
Epoch 818/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.7125
Epoch 819/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.7112
Epoch 820/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.7100
Epoch 821/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.7087
Epoch 822/2000
1/1 [=======================

1/1 [==============================] - 0s 3ms/step - loss: 7.4836
Epoch 1013/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4825
Epoch 1014/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4814
Epoch 1015/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4803
Epoch 1016/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4792
Epoch 1017/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4781
Epoch 1018/2000
1/1 [==============================] - 0s 5ms/step - loss: 7.4770
Epoch 1019/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4759
Epoch 1020/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4749
Epoch 1021/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4738
Epoch 1022/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.4727
Epoch 1023/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.4716
Epoch 1024/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 7.3791
Epoch 1113/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.3781
Epoch 1114/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.3771
Epoch 1115/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.3761
Epoch 1116/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3751
Epoch 1117/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.3741
Epoch 1118/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.3731
Epoch 1119/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.3721
Epoch 1120/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.3711
Epoch 1121/2000
1/1 [==============================] - 0s 5ms/step - loss: 7.3701
Epoch 1122/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3691
Epoch 1123/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.3681
Epoch 1124/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 7.2828
Epoch 1213/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.2819
Epoch 1214/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.2810
Epoch 1215/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.2801
Epoch 1216/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.2792
Epoch 1217/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.2782
Epoch 1218/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.2773
Epoch 1219/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.2764
Epoch 1220/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.2755
Epoch 1221/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.2746
Epoch 1222/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.2736
Epoch 1223/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.2727
Epoch 1224/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 7.1942
Epoch 1313/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1933
Epoch 1314/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.1925
Epoch 1315/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1916
Epoch 1316/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1908
Epoch 1317/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.1899
Epoch 1318/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.1891
Epoch 1319/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1883
Epoch 1320/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1874
Epoch 1321/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1866
Epoch 1322/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1857
Epoch 1323/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1849
Epoch 1324/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 7.1125
Epoch 1413/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.1117
Epoch 1414/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1109
Epoch 1415/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.1101
Epoch 1416/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1094
Epoch 1417/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1086
Epoch 1418/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1078
Epoch 1419/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1070
Epoch 1420/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1062
Epoch 1421/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.1055
Epoch 1422/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1047
Epoch 1423/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.1039
Epoch 1424/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 7.0372
Epoch 1513/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.0365
Epoch 1514/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0357
Epoch 1515/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.0350
Epoch 1516/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.0343
Epoch 1517/2000
1/1 [==============================] - 0s 2ms/step - loss: 7.0336
Epoch 1518/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.0329
Epoch 1519/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.0322
Epoch 1520/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.0314
Epoch 1521/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.0307
Epoch 1522/2000
1/1 [==============================] - 0s 3ms/step - loss: 7.0300
Epoch 1523/2000
1/1 [==============================] - 0s 4ms/step - loss: 7.0293
Epoch 1524/2000
1/1 [===========

1/1 [==============================] - 0s 4ms/step - loss: 6.9678
Epoch 1613/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.9671
Epoch 1614/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.9664
Epoch 1615/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.9658
Epoch 1616/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.9651
Epoch 1617/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.9644
Epoch 1618/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.9638
Epoch 1619/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.9631
Epoch 1620/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.9625
Epoch 1621/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.9618
Epoch 1622/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.9611
Epoch 1623/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.9605
Epoch 1624/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 6.9037
Epoch 1713/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.9031
Epoch 1714/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.9025
Epoch 1715/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.9019
Epoch 1716/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.9013
Epoch 1717/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.9007
Epoch 1718/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.9001
Epoch 1719/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8994
Epoch 1720/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8988
Epoch 1721/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8982
Epoch 1722/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8976
Epoch 1723/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.8970
Epoch 1724/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 6.8447
Epoch 1813/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8441
Epoch 1814/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8435
Epoch 1815/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.8430
Epoch 1816/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8424
Epoch 1817/2000
1/1 [==============================] - 0s 5ms/step - loss: 6.8419
Epoch 1818/2000
1/1 [==============================] - 0s 2ms/step - loss: 6.8413
Epoch 1819/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8407
Epoch 1820/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8402
Epoch 1821/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.8396
Epoch 1822/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8390
Epoch 1823/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.8385
Epoch 1824/2000
1/1 [===========

1/1 [==============================] - 0s 3ms/step - loss: 6.7902
Epoch 1913/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7897
Epoch 1914/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7892
Epoch 1915/2000
1/1 [==============================] - 0s 6ms/step - loss: 6.7886
Epoch 1916/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7881
Epoch 1917/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7876
Epoch 1918/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.7871
Epoch 1919/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7865
Epoch 1920/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7860
Epoch 1921/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7855
Epoch 1922/2000
1/1 [==============================] - 0s 4ms/step - loss: 6.7850
Epoch 1923/2000
1/1 [==============================] - 0s 3ms/step - loss: 6.7845
Epoch 1924/2000
1/1 [===========

In [12]:
print(tf.model.predict([[100., 70., 98.]]))

1/1 [==============================] - 0s 74ms/step
[[178.72472]]
